### ISSUE TITLE
followed instructions but netlify dev fails

### ISSUE THREAD

**Issue by Maxhodges** [philhawksworth/eleventail#6]
```
◈ Netlify Dev ◈
Error: "framework" option must be set to "#custom" when specifying both "command" and "targetPort" options
    at module.exports.serverSettings (~/.nvm/versions/node/v12.13.0/lib/node_modules/netlify-cli/src/utils/detect-server.js:64:13)
    at DevCommand.run (~/.nvm/versions/node/v12.13.0/lib/node_modules/netlify-cli/src/commands/dev/index.js:424:26)
    at async DevCommand._run (~/.nvm/versions/node/v12.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (~/.nvm/versions/node/v12.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (~/.nvm/versions/node/v12.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (~/.nvm/versions/node/v12.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)


```

**Comment by tomhermans** [comment]
Add   framework = "#custom" to netlfiy.toml file

`[build]
  command = "npm run build"
  publish = "dist"
  # functions = "./src/functions"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }


[dev]
  command = "npm run start"
  framework = "#custom"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  # functionsPort = 34567

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
`

**Comment by philhawksworth** [comment]
Good catch. Thanks for reporting this @Maxhodges! 
And thanks for the speedy fix, @tomhermans. Merged!
